### ISSUE TITLE
code base uploaded every time 

### ISSUE THREAD

**Issue by evalsocket** [floydhub/floyd-cli#125]
The whole codebase uploaded every time whenever I run the job. We run a job, again and again, for iterating with different hyperparameter. 
If I change one file and run the job then Floyd cli will upload whole code base and then run the job but it would be great if only one file will be uploaded like git 

can we make it `git push floyd master`
When we are using `floyd init project_name` then we can initialize remote floyd on git  `git remote add floyd https://git.floydhub.com/project_name.git`

every job has their own commit id for iterate and past history

**Comment by houqp** [comment]
Hi, thanks for the feedback! Tight git integration is something we have been considering internally. However, it's not currently not a high priority item in the queue right now. So we can't give you a timeline on when it will be ready. We will definitely go back to it when we have resources to work on this feature.
