### ISSUE TITLE
`floyd run --data xxx:yyy` fails in new `floyd-cli==0.10.19` (but is fine in previous version)

### ISSUE THREAD

**Issue by ig248** [floydhub/floyd-cli#135]
Running `floyd run --data path/to/dataset:data` throws `Error: Missing .floyddata file, run floyd data init first`. The same command works fine in the same folder after downgrading back to 0.10.18.

**Comment by houqp** [comment]
Thanks for the report, we will be pushing out a hotfix version soon.

**Comment by houqp** [comment]
I have released a new version to address this issue, thanks again for the report!

**Comment by ig248** [comment]
Thanks for the quick fix, the extra typing in shell will no longer distract me from spending precious GPU minutes :)

**Comment by houqp** [comment]
Glad that you liked the simplification! Kudos to @mckayward :)
