### ISSUE TITLE
Running a job with a CPU2 instance

### ISSUE THREAD

**Issue by fiquinho** [floydhub/floyd-cli#145]
Hi, I just purchased hours of the CPU2 instance, but I can't use them in my jobs, the --cpu2 command is not recognized.

Maybe it's not supposed to be used like that.

Thanks in advance!

Federico

**Comment by houqp** [comment]
Hi, sorry for the confusion, you need to upgrade your cli to the latest version to use --gpu2 flag. We are going to push out a reminder to users using old version of cli today to remind them for the upgrade.

**Comment by fiquinho** [comment]
Hi thanks for the quick response!

I upgraded the client before trying, but it doesn't work. And I'm having issues with CPU2 not GPU2.

Maybe I'll try to uninstall the client and installing it back. I'll let you know if it works.

Thanks again!

**Comment by houqp** [comment]
@fiquinho any luck? Could you let us know what version of the CLI you were using?

**Comment by fiquinho** [comment]
Hey! I successfully ran my job with CPU2. It works with:
`floyd-cli-0.10.27`

Thanks!
