### ISSUE TITLE
Command Does Net Exist 

### ISSUE THREAD

**Issue by jaeseung172** [floydhub/floyd-cli#15]
I've Installed Floyd-Cli on Ubuntu 17.04 using Pypi-Installer (Python3.5) 

But When I type command, Terminal Says "Command Does Not Exist"

How Can I solve This Problem?

**Comment by mckayward** [comment]
Hey @jaeseung172,

Could you give some more detail on how you attempted the installation? What steps did you take? What were the outputs of the commands you ran? Also, this may seem silly, but what command are you running that gives you the message "Command Does Not Exist"?

**Comment by jaeseung172** [comment]
I've Just Type `floyd` And Then They Says Nothing! haha...

**Comment by jaeseung172** [comment]
But I've Finished Install Using Virtualenv... Thanks.
