### ISSUE TITLE
Add `logs -f` flag   

### ISSUE THREAD

**Issue by msoedov** [floydhub/floyd-cli#152]
Currently there is a `floyd logs -t (tail)` which was kind of confusing for me. I believe many of people with Linux/Unix background get used to  -f/--follow convention, such as  `tail -f`  and `docker logs -f`, etc...

I would like to ask you to add a `-f` flag to current cli app interface.

Thank you for your awesome product!

**Comment by houqp** [comment]
Thanks for the feedback! This can be easily added to the cli around https://github.com/floydhub/floyd-cli/blob/master/floyd/cli/experiment.py#L144. Are you interested in contributing a patch? I would be more than happy to review the PR.

**Comment by msoedov** [comment]
I will take a look later today :)

**Comment by houqp** [comment]
feature already pushed out, closing this issue for now.
