### ISSUE TITLE
GPU2 not working

### ISSUE THREAD

**Issue by ParthasarathySubburaj** [floydhub/floyd-cli#160]
Hi, I just purchased gpu2 and tried to restart my job in gpu2 instance with tensorflow1.3 environment but it says "unknown environment received:gpu2 Tensorflow1.3". 
Kindly let me know what the issue is
Thanks.

**Comment by saiprashanths** [comment]
What command did you issue that returned the error? 

Closing this issue. Please email us at support@floydhub.com with your username, so we can provide more contextual support. (we'll keep this forum for issues related to the CLI :) )
