### ISSUE TITLE
upload does not start

### ISSUE THREAD

**Issue by soerendip** [floydhub/floyd-cli#163]
I am new to floyd. Trying to upload my first dataset. I created the dataset in the dashboard and initiated it on my PC. Working from an Linux Subsystem Terminal in Windows10 (Ubuntu).

```
>floyd data upload
An unfinished upload exists. Would you like to resume it? [y/N]: N
Compressing data...
Making create request to server...
Initializing upload...
Uploading compressed data. Total upload size: 161.2MiB
[                                ] 0/169023422 - 00:00:00
```

It stays like this for several minutes. Looking like the upload does not start.

**Comment by soerendip** [comment]
Ok, it is moving slowly. Seems it just does not update very frequently.

**Comment by houqp** [comment]
Hi, it's mostly like due to slow network speed between you and our servers. If the data is available publicly, you can spin up a job and download it directly into floydhub instead. That would be a lot faster. Then you can promote the job output into a dataset.

**Comment by korantu** [comment]
*Update:* uploading from an AWS machine worked OK, it seems my home connection is not so good.

I have the same issue, for just 13Mb upload and generaly decent internet connection ( Upload Speed 37 Mbps, as reported by http://fast.com ):

```
Compressing 2536 files
Compressing data...
[================================] 2536/2536 - 00:00:01
Making create request to server...
Initializing upload...
Uploading compressed data. Total upload size: 13.2MiB
[                                ] 0/13805997 - 00:00:00

```

It stays like this for several minutes, and nothing changes. Is there any better ways to get custom training sets into your system?

PS: as @soerendip mentioned, it does progress, but super-slow, making it not very useful
