### ISSUE TITLE
'floyd data upload' - file is not uploading.

### ISSUE THREAD

**Issue by helloworld2394** [floydhub/floyd-cli#173]
I'm uploading a dataset with size of about 105GiB. But nothing is uploaded in an hour.
There was no problem with the network connection.
```
An unfinished upload exists. Would you like to resume it? [y/N]: y
Uploading compressed data. Total upload size: 105.6GiB
[                                ] 0/113364204398 - 17:09:33
```
How can I upload a dataset immediately?

**Comment by houqp** [comment]
Hi, given that our machine only comes with 100GB disk, even if you are able to upload this dataset, you won't be able to use it :( Would it be possible for you to split it into multiple parts or trim it?

If the dataset is publicly available on internet, it would be a lot faster for you to download it directly in a floydhub job and promote the output into a dataset.

**Comment by helloworld2394** [comment]
But I can use up to 200GB as an account upgrade.
