### ISSUE TITLE
[Feature Request] Allow selective staging of files like.

### ISSUE THREAD

**Issue by abishekk92** [floydhub/floyd-cli#2]
_floydcli_ currently syncs all the files recursively inside the project directory by default and the only way to prevent this behavior seems to be adding these files/directories into `.floydignore`.  Instead, would you consider allowing users to stage files specific to their experiments?

**Comment by narenst** [comment]
Yes @abishekk92, we are planning to move towards a git model soon - it is pretty close the top of our feature roadmap. Users can specifically add any code relevant to their project and do a "floyd push".

**Comment by narenst** [comment]
In the meantime, the workaround is to create separate projects in subdirectories to avoid uploading all the code.

**Comment by narenst** [comment]
We have since changed the priorities of features in the roadmap. If folks are still interested in this please add it to [FloydHub forum](https://forum.floydhub.com/).
