### ISSUE TITLE
Data download fails

### ISSUE THREAD

**Issue by bartolsthoorn** [floydhub/floyd-cli#20]
My `download_data.sh` contains:
```
wget *****/train-jpg.tar.gz
mkdir output
tar -xvzf train-jpg.tar.gz -C output
```
I run this with `floyd run "sh download_data.sh"`, it runs successfully (and I see many jpg files in the logs), but afterwards there is no data reported in usage (https://www.floydhub.com/usage) and I can not load it as input to a jupyter notebook.

What went wrong here?

Also note that in [http://docs.floydhub.com/home/using_datasets/](http://docs.floydhub.com/home/using_datasets/) the docs skip over what actually should be in `download_data.sh`, it would be good to give an example there.

**Comment by narenst** [comment]
Hey, thanks for reporting this issue. You need to send the output to `/output/..` path for floyd to save it.

Remember we are using the github issues here to track problems related to floyd-cli project only. Please send an email to support@floydhub.com to report issues/comments on the platform itself.

**Comment by bartolsthoorn** [comment]
Ah so `output` should be `/output`, thanks!
