### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by dalmia** [floydhub/floyd-cli#25]
I tried installing `floyd-cli` through `pip` as mentioned in the website. I encounter this error:
```
#include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__
='/tmp/pip-build-xzvbSD/scandir/setup.py';f=getattr(tokenize, 'open', open)(__file__);
code=f.read().replace('\r\n', '\n');f.close();
exec(compile(code, __file__, 'exec'))" install --record 
/tmp/pip-Eu9cG6-record/install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in /tmp/pip-build-xzvbSD/scandir/
```
Please let me know what am I doing wrong.

**Comment by mckayward** [comment]
@dalmia Looks like you are missing the `<Python.h>` header files necessary for building scandir. You can get them by installing `python-dev` with your package manager:

```sudo apt-get install python-dev```

Or, if you're using python3:

```sudo apt-get install python3-dev```

If that doesn't work for you, could you give more information about your environment setup and the process you followed that led to the error?

**Comment by dalmia** [comment]
@mckayward Thank you very much. It's working now :+1:
