### ISSUE TITLE
Invalid response from FloydHub server.134109 - 00:00:001:32

### ISSUE THREAD

**Issue by iamharshit** [floydhub/floyd-cli#35]
I am getting the above error when i am trying to upload a file of size 5.3 GB on the trial version of floydhub.What may be the problem, I guess it exceeds the Maximum Upload Size in Floydhub? @
![screenshot from 2017-06-12 17 43 28](https://user-images.githubusercontent.com/15041829/27033527-529033c4-4f97-11e7-8471-4a2f620b6842.png)

**Comment by narenst** [comment]
Hey, some of our users are currently seeing this issue when uploading large datasets. So we are currently re-working the upload framework and hope to release it very soon. Sorry for the inconvenience.

**Comment by mckayward** [comment]
This should be solved with release 0.9.8.
Let us know if you still have issues.
