### ISSUE TITLE
Tool reports that a new version is available when it's not

### ISSUE THREAD

**Issue by jmeakin** [floydhub/floyd-cli#51]
Really minor bug. I have floyd-cli version 0.9.9 installed. When running `floyd init project` the tool tells me

```
$ floyd init project

New version of CLI (0.9.7) is now available. To upgrade run:
    pip install -U floyd-cli
            
Project "project" initialized in current directory
```
This is not the case, and running that pip command (obviously) does nothing. Steps to reproduce:

```
virtualenv venv
source venv/bin/activate
pip install -U floyd-cli
floyd login
floyd init project
```
Pip freeze:

```
args==0.1.0
certifi==2017.4.17
chardet==3.0.4
click==6.7
clint==0.5.1
floyd-cli==0.9.9
idna==2.5
marshmallow==2.13.5
pathlib2==2.3.0
pytz==2017.2
requests==2.18.1
requests-toolbelt==0.8.0
shortuuid==0.5.0
six==1.10.0
tabulate==0.7.7
urllib3==1.21.1
```

Python 3.5.3, virtualenv 15.1.0 on Fedora 4.11.8-200.fc25.x86_64

**Comment by houqp** [comment]
Hi! Thanks for the report, I forgot to push out the server config to update the latest client, it's pointed at 0.9.7 right now, but we have 0.9.9 published on pypi. I will get that fixed as soon as possible.

**Comment by houqp** [comment]
This issue should have been resolved.

**Comment by jmeakin** [comment]
This is still unresolved in version 0.9.10:

```
$ pip freeze    
args==0.1.0
certifi==2017.4.17
chardet==3.0.4
click==6.7
clint==0.5.1
floyd-cli==0.9.10
idna==2.5
marshmallow==2.13.5
pathlib2==2.3.0
pytz==2017.2
requests==2.18.1
requests-toolbelt==0.8.0
shortuuid==0.5.0
six==1.10.0
tabulate==0.7.7
urllib3==1.21.1
$ floyd run --env tensorflow --mode jupyter 


New version of CLI (0.9.10) is now available. To upgrade run:
    pip install -U floyd-cli
```

**Comment by jmeakin** [comment]
Ok, I've worked this out. In my system python environment I had floyd-cli 0.8.9 installed, and the latest one in a virtual env. Despite `which floyd-cli` reporting that the executable used is the one in virtual env, the one in the system python must have been executed.
