### ISSUE TITLE
getting error while login

### ISSUE THREAD

**Issue by subhayu89** [floydhub/floyd-cli#64]
(tensorflowgpu) subhayu@subhayu-Lenovo-Z580:~$ floyd login 
Error: 
Your version of CLI (0.9.9) is no longer compatible with server. Run:
    pip install -U floyd-cli
to upgrade to the latest version (0.10.1)
I have updated the cli also...

floyd-cli                 0.10.2                    <pip>

**Comment by saiprashanths** [comment]
Can you paste the exact logs you see when you run `floyd version`?

**Comment by subhayu89** [comment]
exact logs were you should update the cli to 0.10.2 which i alread had.

Somehow it is working now.For past 12 hrs it was throwing same error

**Comment by saiprashanths** [comment]
Not sure what the issue was, but glad it is resolved! :)

**Comment by wassimseif** [comment]
Guys I'm getting the same error using the latest release.
It used to happen about a week ago, then it magically worked, now it's happening again
