### ISSUE TITLE
`floyd delete` does not delete Experiment Output Data

### ISSUE THREAD

**Issue by TariqAHassan** [floydhub/floyd-cli#66]
Hello,

This could be a misunderstanding on my part, but `floyd delete` does not delete *output* data.
Trying to delete data via. the web interface has the same problem.

**Comment by SreenivasVRao** [comment]
Adding to this, before the floyd CLI was updated, `floyd data status` would show both outputs stored as well as datasets uploaded.

After the update, I can't see the status of outputs through the CLI anymore.

Like @TariqAHassan, I'm able to delete the jobs which created the output using `floyd data delete`, however, I'm not able to delete the output itself.

Would like the option to see them through the CLI again. That was very useful.

**Comment by narenst** [comment]
Hey, we have made a slight change to FloydHub recently - when you delete the experiment, the output data is deleted along with it. You no longer have to delete the output data separately. Please let us know if you are not seeing that behavior.

**Comment by TariqAHassan** [comment]
Yes, that does appear to be fixed -- thanks!
However, deleting an entire project does not appear to causes all experiments therein to be deleted (along with their associated data).
