### ISSUE TITLE
Issue installing floyd-cli

### ISSUE THREAD

**Issue by AdamBCo** [floydhub/floyd-cli#68]
I keep getting the following error when running the installation command:

I have included a gist of the errror logs: [https://gist.github.com/AdamBCo/ee16fe5f5ba47aae7074925852ccf9d0](url)

**Comment by narenst** [comment]
Hey @AdamBCo, Can you try installing the cli inside a virtualenv? That helps avoid version conflict issues. See our docs page for more info: http://docs.floydhub.com/faqs/installation/#using-virtualenv-to-install-floyd-cli

**Comment by narenst** [comment]
Closing for now, please reopen if you see this issue inside virtualenv. Alternatively you can also install globally by using sudo option:

`sudo pip install -U floyd-cli`

**Comment by AdamBCo** [comment]
@narenst The virtualenv solution worked, so thank you for the help!
