### ISSUE TITLE
check_cli_version should only be called if verbose flag is set

### ISSUE THREAD

**Issue by rmdort** [floydhub/floyd-cli#84]
Shouldn't `check_cli_version` be called only if `verbose` flag is supplied by the user?

**Comment by houqp** [comment]
We are using this to push major client incompatible upgrade from the our server so it needs to be checked every time unfortunately. There is a more efficient way to implement this logic and avoid that extra API call when starting the client, but we haven't had time to implement it yet. I will keep this issue open as a reminder for the optimization.

**Comment by rmdort** [comment]
This kind of defeats the purpose of having a `format` option in the CLI. #81

**Comment by houqp** [comment]
Closing this for now since you managed to find a better way to automate your workflow.

May I ask what kind of automation are you building around FloydHub? Depending on the use-case, we might be able to build it into FloydHub for you.

**Comment by rmdort** [comment]
@houqp Sure. I am creating an end-to-end training + serving pipeline for our ML projects. 

1. We have a training server in K8, that creates a floyd job 
2. We poll every 1 min for the status of the job and get the output URI
3. We deploy serving containers in K8 and each container download the models from floyd

Pretty straighforward. I guess floyd module API's are working fine for me now :)
