### ISSUE TITLE
API to refresh token

### ISSUE THREAD

**Issue by rmdort** [floydhub/floyd-cli#88]
Can floyd add an API to refresh token?

`.floydconfig` file has the token expiry date. Prior to the expiry date, we want to refresh the token using an API call.

**Comment by houqp** [comment]
Right now the web UI uses the login api to get a new token. We have plan to add username/password login to the cli soon. I will update this issue once it's implemented.

**Comment by narenst** [comment]
@rmdort We just released login using credentials. Can you try this: https://github.com/floydhub/floyd-cli/releases/tag/v0.10.18

**Comment by narenst** [comment]
Closing this now since the cli supports credentials based login.
