### ISSUE TITLE
Data attaching issue

### ISSUE THREAD

**Issue by sachinruk** [floydhub/floyd-cli#93]
The following command `floyd run --data sachinruk/datasets/trump_tweets/1:/data/ --gpu --env tensorflow-1.0 --mode jupyter` gives me the error: `Error: Internal FloydHub server error.`

However, if I do not attach data to this, it works fine. i.e. `floyd run --gpu --env tensorflow-1.0 --mode jupyter` works.

Any thoughts?

**Comment by houqp** [comment]
seems like an issue specific to your dataset, I am debugging this now.

**Comment by saiprashanths** [comment]
The issue is that you entered `/data` as your mount point. Can you please just use `data` (without the preceeding slash)?

This is a minor bug on our end. We'll fix this, or at least give a more informative error message.

**Comment by houqp** [comment]
Closing this for now since it's already fixed.
